version: 2.1
jobs:
  eslint-job:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run eslint
  test-job:
    docker:
      - image: node:latest
    steps:
      - run: npm install
      - run: npm run test
  build-job:
    docker:
      - image: node:latest
    steps:
      - run: npm install
      - run: npm run build
  deploy-job:
    docker:
      - image: node:latest
    steps:
      - run: npm install
      - run: npm run deploy

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - eslint-job
      - test-job:
          requires:
            - eslint-job
      - build-job:
          requires:
            - eslint-job
            - test-job
      - hold:
          type: approval
          requires:
            - eslint-job
            - test-job
            - build-job
      - deploy-job:
          requires:
            - hold
