version: 2.1
jobs:
  build-job:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  deploy-job:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run:
          name: "GIT config"
          command: |
            git config --global user.email "${CIRCLE_USERNAME}@users.noreply.github.com"
            git config --global user.name "${CIRCLE_USERNAME}"
      - run: npm run deploy

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
