version: 2.1
jobs:
  eslint-job:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run eslint
  test-job:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  build-job:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  deploy-job:
    docker:
      - image: node:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: git config --global user.email "chubatyuk02@gmail.com"
      - run: git config --global user.name "Chubatik"
      - run: npm run deploy

workflows:
  version: 2
  deploy-workflow:
    jobs:
      - eslint-job
      - test-job:
          requires:
            - eslint-job
      - build-job:
          requires:
            - eslint-job
            - test-job
      - hold_1:
          type: approval
          requires:
            - eslint-job
            - test-job
            - build-job
          filters:
            branches:
              only: master
      - hold_2:
          type: approval
          requires:
            - eslint-job
            - test-job
            - build-job
            - hold_1
          filters:
            branches:
              only: master
      - deploy-job:
          requires:
            - hold_1
            - hold_2
          filters:
            branches:
              only: master
