version: 2.1
jobs:
  eslint:
    docker:
      - image: node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

            - run: npm install

            - save_cache:
                paths:
                  - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run eslint

  test:
    docker:
      - image: node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm run test

  build:
    docker:
      - image: node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm run build

  deploy:
    docker:
      - image: node:latest

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm run deploy

workflow:
 jobs:
  - eslint
  - test:
      requires:
        - eslint
  - build:
      requires:
        - eslint
        - test
  - hold:
      type: approval
      requires:
        - eslint
        - test
        - build
  - deploy:
      requires:
        - hold
